config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  root 'home#index'
  get 'home/about' => 'home#about', as: 'about'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :create, :show, :edit, :update] do
    get 'follows' => 'relationships#follows', as: 'follows'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, :body, presence: true
  validates :body, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得 
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人 #自分をfollowしている人  throughで上のfollowedと関連付け
  
  # followする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  # unfollowする
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  
  
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :cofigure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     user_path(current_user.id) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end


  def cofigure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    
    def create
        book = Book.find(params[:book_id])
        comment = current_user.book_comments.new(book_comment_params)
        comment.book_id = book.id
        if comment.save
            redirect_to book_path(book)
        else
            redirect_back(fallback_location: root_path)
        end
        
    end
    
    def destroy
        BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
        redirect_back(fallback_location: root_path)
    end
  
    private
    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

    def new
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            flash[:success] = "You have created book successfully."
            redirect_to book_path(@book)
        else
            @user = current_user
            @books = Book.all
            render 'index'
        end
    end

    def index
        @book = Book.new
        @books = Book.all
        @user = current_user
    end

    def show
        @book_new = Book.new
        @book = Book.find(params[:id])
        @user = User.find(@book.user_id)
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
        if @book.user_id != current_user.id
            redirect_to books_path
        end

    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:suscess] = "You have updated book successfully."
            redirect_to book_path(@book)
        else
            
            render 'edit'
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to  books_path
    end

    private
    def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!



    def index
        @book = Book.new
        @users = User.all
        @user = current_user
    end

    def create
        @book = Book.new(user_params)
        user = current_user
        @book = user.book
        if @book.save
            flash[:success] = "You have created book successfully."
            redirect_to book_path(@book)
        else
            @books = Book.all
            render 'index'
        end
    end

    def show
        @book_new = Book.new
        @user = User.find(params[:id])
        @books = @user.books
    end

    def edit
        @user = User.find(params[:id])
        if @user.id != current_user.id
            redirect_to user_path(current_user)
        end
    end
    

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "You have updated user successfully."
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end


    private
    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books.1/_list.html.erb
<div class="user_info">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= user.follower.count %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= user.followed.count %></th>
        </tr>
        
      </tbody>
    </table>
    <div class="row">
      <% if user == current_user %>
        <%= link_to edit_user_path(current_user.id) do %>
          <button type="button" class="col-xs-12 btn btn-default edit_user_25037">
            <i class="glyphicon glyphicon-wrench"></i>
          </button>
        <% end %>
      <% else %>
        <% unless current_user == user %>
          <% if current_user.following?(user) %>
            <%=  form_with model: relationship, url: unfollow_path(user.id) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'フォロー外す', class: 'btn btn-primary' %>
            <% end %>
          <% else %>
            <%= form_with model: relationship, url: follow_path(user.id) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'フォローする', class: 'btn btn-success' %>
            <% end %>
          <% end %>
          
        <% end %>
      <% end %>
    </div>    
</div>
<div class="new_book">
  <h2>New book</h2>
  <%= form_with model: book, local:true do |f| %>
    <div class="field row">
      <div >
        <label>Title</label></br>
        <%= f.text_field :title, class: "col-xs-12" %>
      </div>
    </div>
    <div class="field row">
      <div>
        <label>Opinion</label></br>
        <%= f.text_area :body, class: "col-xs-12" %>
      </div>
    </div>
    <div class="actions row">
      <%= f.submit "Create Book",class:"btn btn-primary col-xs-12" %>
    </div>
  <% end %>
</div>

app/views/books.1/edit.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation">
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
<% end %>
        </ul>
    </div>
<% end %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <%= form_with model: @book, local:true do |f| %>
            <div class="field row">
                <div>
                    <label>Title</label></br>
                    <%= f.text_field :title, class:"col-xs-12" %>
                </div>
            </div>
            <div class="field row">
                <div>
                    <label>Opinion</label></br>
                    <%= f.text_area :body, class:"col-xs-12" %>
                </div>
            </div>
            <div class="actions row">
                <%= f.submit "Update Book", class:"btn btn-primary col-xs-12" %>
            </div>
        <% end %>
        <%= link_to 'Show', book_path %> |
        <%= link_to 'Back', books_path %>
    </div>
    <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
    </div>
</div>

app/views/books.1/index.html.erb
            <% flash.each do |message_type, message| %>
                <%= message %>
            <% end %>
            <% if @book.errors.any? %>
                <div id="error_explanation">
                    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="row">

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3" >
                    <%= render 'books/list', user: @user, book: @book %>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9 ">
                    <h2>Books</h2>
                    <table class="table table-hover table-inverse">
                        <thead>
                          <tr>
                              <th></th>
                              <th>Title</th>
                              <th>Opinion</th>
                              <th></th>
                          </tr>
                        </thead>
                        <tbody>
                            <% @books.each do |book| %>
                                <tr>
                                    <td>
                                        <%= link_to user_path(book.user) do %>
                                            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %>
                                        <% end %>
                                    </td>
                                    <td>
                                        <%= link_to book_path(book.id) do %>
                                            <%= book.title %>
                                        <% end %>
                                    </td>
                                    <td><%= book.body %></td>
                                    <td>
                                        <% if book.favorited_by?(current_user) %>
                                            
                                                <%= link_to book_favorites_path(book), method: :delete do %>
                                                    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                                                    <%= book.favorites.count %>
                                                <% end %>
                                           
                                        <% else %>
                                            
                                                <%= link_to book_favorites_path(book), method: :post do %>
                                                    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                                                    <%= book.favorites.count %>
                                                <% end %>
                                            
                                        <% end %>
                                    </td>
                                    <td> コメント数:<%= book.book_comments.count %></td>
                                </tr>
                            <% end %>
                        </tbody>


                    </table>
                </div>
            </div>

app/views/books.1/show.html.erb
    <div class="row">
        
        <div class="col-xs-3" >
            <%= render 'books/list', user: @user, book: @book_new %>
        </div>
        <div class="col-xs-9 ">
            <h2>Book detail</h2>
            <table class="table">
                <thead>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@user) do %>
                                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40 %>
                                <p><%= @user.name %></p>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to book_path(@book) do %>
                                <%= @book.title %>
                            <% end %>
                        </td>
                        <td><%= @book.body %></td>
                        <% if @book.user == current_user %>
                            <td><%= link_to 'Edit', edit_book_path(@book.id), class:"btn-sm btn-success" %></td>
                            <td><%= link_to 'Destroy', book_path(@book.id), class:"btn-sm btn-danger", method: :delete, data: { confirm: "本当に消しますか？" } %></td>
                        <% else %>
						    <td>
						        <% if @book.favorited_by?(current_user) %>
                                    <%= link_to book_favorites_path(@book), method: :delete do %>
                                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                                        <%= @book.favorites.count %>
                                    <% end %>
                                           
                                <% else %>
                                            
                                    <%= link_to book_favorites_path(@book), method: :post do %>
                                        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                                        <%= @book.favorites.count %>
                                    <% end %>
                                            
                                <% end %>
                            </td>
						    <td>コメント数:<%= @book.book_comments.count%></td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
            
            <% @book.book_comments.each do |book_comment| %>
                <p>
                    <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50') %>
                    <%= book_comment.comment %>
                    <% if book_comment.user == current_user %>
			             <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), class:"btn-sm btn-danger", method: :delete %>
				    <% end %>
				</p>
			<% end %>	
            
		    <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
		        <div class="row">                       
				    <div class="col-xs-11">	
                        <%= f.text_area :comment, rows:'5', class:"form-control" %>
					    <%= f.submit '送信' %>
				    </div>
		        </div>
		    <% end %>
		</div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">

          <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
          </nav>

          <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
                <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %></li>
                <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %></li>
                <li><%= link_to " logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out logout", method: :delete %></li>
              <% else %>
                <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
                <li><%= link_to ' About', about_path, class: "glyphicon glyphicon-link about" %></li>
                <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
                <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
              <% end %>
            </ul>
          </nav>
        </div>
    </header>
    <div class="body">
      <div class="container">
        <% flash.each do |message_type, message| %>
          <p><%= message %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          CopyRight Infratop.inc
        </div>
      </div>
    </div>
  </footer>
</html>